PYTHONPATH=. python scripts/reward_custom_sample_and_render.py \
dataset=custom_scene \
dataset.processed_scene_data_path=data/metadatas/custom_scene_metadata.json \
dataset.max_num_objects_per_scene=12 \
+num_scenes=256 \
algorithm=scene_diffuser_flux_transformer \
experiment.find_unused_parameters=True \
algorithm.classifier_free_guidance.use=False \
algorithm.classifier_free_guidance.weight=0 \
algorithm.num_additional_tokens_for_sampling=0 \
algorithm.custom.loss=true \
algorithm.noise_schedule.ddim.num_inference_timesteps=150 \
algorithm.trainer=ddpm \
load=7m2291fu \
algorithm.noise_schedule.scheduler=ddpm \
algorithm.ema.use=False