#!/usr/bin/env bash
# PYTHONPATH=. python scripts/custom_sample_and_render.py +num_scenes=1000 \
# load=2cnwjcuy \
# dataset=custom_scene \
# dataset.processed_scene_data_path=data/metadatas/custom_scene_metadata.json \
# dataset.max_num_objects_per_scene=12 \
# experiment.test.batch_size=32 \model-toid1beb
# algorithm=scene_diffuser_flux_transformer \
# algorithm.trainer=rl_score \
# algorithm.noise_schedule.scheduler=ddim \
# algorithm.noise_schedule.ddim.num_inference_timesteps=150 \
# experiment.find_unused_parameters=True \
# algorithm.classifier_free_guidance.use=False \
# algorithm.classifier_free_guidance.use_floor=False \
# algorithm.classifier_free_guidance.weight=0 \
# algorithm.custom.loss=true \
# algorithm.ema.use=True \
# dataset.data.encoding_type=cached_diffusion_cosin_angle_wocm_no_prm \


# python ../ThreedFront/scripts/render_results.py --no_texture --without_floor --retrieve_by_size /media/ajad/YourBook/AshokSaugatResearchBackup/AshokSaugatResearch/steerable-scene-generation/outputs/2025-11-28/13-24-17/sampled_scenes_results.pkl
# python ../ThreedFront/scripts/render_results.py --no_texture --retrieve_by_size /media/ajad/YourBook/AshokSaugatResearchBackup/AshokSaugatResearch/steerable-scene-generation/outputs/2025-11-27/11-34-36/trajectories/trajectory_seed150698782.pkl

# python ../ThreedFront/scripts/render_results.py --no_texture --retrieve_by_size /media/ajad/YourBook/AshokSaugatResearchBackup/AshokSaugatResearch/steerable-scene-generation/outputs/2025-11-30/11-43-57/sampled_scenes_results.pkl

    # load=fhfnf4xi \
# PYTHONPATH=. python dynamic_constraint_rewards/get_reward_stats.py \

# export WANDB_ENTITY="078bct081-saugat"

PYTHONPATH=. python -u  main.py +name=test \
    load=pcnfeqr0 \
    checkpoint_version=20 \
    dataset=custom_scene \
    dataset.processed_scene_data_path=data/metadatas/custom_scene_metadata.json \
    dataset.max_num_objects_per_scene=12 \
    algorithm=scene_diffuser_midiffusion \
    algorithm.classifier_free_guidance.use=False \
    algorithm.ema.use=True \
    algorithm.trainer=rl_score \
    algorithm.noise_schedule.scheduler=ddim \
    algorithm.noise_schedule.ddim.num_inference_timesteps=150 \
    experiment.training.max_steps=1050000 \
    experiment.validation.limit_batch=1 \
    experiment.validation.val_every_n_step=50 \
    algorithm.ddpo.ddpm_reg_weight=100.0 \
    experiment.reset_lr_scheduler=true \
    experiment.training.lr=1e-6 \
    experiment.lr_scheduler.num_warmup_steps=250 \
    experiment.training.checkpointing.every_n_train_steps=500 \
    algorithm.num_additional_tokens_for_sampling=0 \
    algorithm.ddpo.n_timesteps_to_sample=100 \
    experiment.find_unused_parameters=True \
    algorithm.custom.loss=True \
    algorithm.validation.num_samples_to_render=0 \
    algorithm.validation.num_samples_to_visualize=0 \
    algorithm.validation.num_directives_to_generate=0 \
    algorithm.test.num_samples_to_render=0 \
    algorithm.test.num_samples_to_visualize=0 \
    algorithm.test.num_directives_to_generate=0 \
    algorithm.validation.num_samples_to_compute_physical_feasibility_metrics_for=0 \
    algorithm.classifier_free_guidance.use_floor=true \
    algorithm.ddpo.dynamic_constraint_rewards.use=True \
    dataset.sdf_cache_dir=./bedroom_sdf_cache/ \
    dataset.accessibility_cache_dir=./bedroom_accessibility_cache/ \
    algorithm.custom.num_classes=22 \
    algorithm.custom.objfeat_dim=0 \
    algorithm.custom.obj_vec_len=30 \
    algorithm.custom.obj_diff_vec_len=30 \
    dataset.data.encoding_type=cached_diffusion_cosin_angle_wocm \
    dataset.data.dataset_directory=bedroom \
    dataset.data.annotation_file=bedroom_threed_front_splits_original.csv \
    dataset.data.room_type=bedroom \
    algorithm.custom.old=False \
    algorithm.ddpo.dynamic_constraint_rewards.reward_base_dir=/media/ajad/YourBook/AshokSaugatResearchBackup/AshokSaugatResearch/steerable-scene-generation/dynamic_constraint_rewards \
    algorithm.ddpo.dynamic_constraint_rewards.user_query="Bedroom_with_wardrobe_stool" \
    algorithm.ddpo.dynamic_constraint_rewards.agentic=True \
    algorithm.ddpo.dynamic_constraint_rewards.universal_weight=0.0 \
    algorithm.ddpo.batch_size=4 \
    experiment.training.batch_size=4 \
    experiment.validation.batch_size=4 \
    experiment.test.batch_size=4 \
    wandb.mode=disabled \
    algorithm.ddpo.incremental_training=true \
    algorithm.ddpo.training_steps_start=66000 \
    # algorithm.ddpo.incremental_training=false \
    # algorithm.ddpo.training_steps_start=0 \
    # algorithm.ddpo.joint_training=false
# PYTHONPATH=. python main.py +name=test_bed_tv_work \
#     load=ca0l19rv \
#     dataset=custom_scene \
#     dataset.processed_scene_data_path=data/metadatas/custom_scene_metadata.json \
#     dataset.max_num_objects_per_scene=12 \
#     algorithm=scene_diffuser_flux_transformer \
#     algorithm.classifier_free_guidance.use=False \
#     algorithm.ema.use=True \
#     algorithm.trainer=rl_score \
#     algorithm.noise_schedule.scheduler=ddim \
#     algorithm.noise_schedule.ddim.num_inference_timesteps=150 \
#     experiment.training.max_steps=2000000 \
#     experiment.validation.limit_batch=1 \
#     experiment.validation.val_every_n_step=50 \
#     algorithm.ddpo.ddpm_reg_weight=100.0 \
#     experiment.reset_lr_scheduler=True \
#     experiment.training.lr=1e-6 \
#     experiment.lr_scheduler.num_warmup_steps=250 \
#     algorithm.ddpo.batch_size=2 \
#     experiment.training.checkpointing.every_n_train_steps=500 \
#     algorithm.num_additional_tokens_for_sampling=0 \
#     algorithm.ddpo.n_timesteps_to_sample=100 \
#     experiment.find_unused_parameters=True \
#     algorithm.custom.loss=True \
#     algorithm.validation.num_samples_to_render=0 \
#     algorithm.validation.num_samples_to_visualize=0 \
#     algorithm.validation.num_directives_to_generate=0 \
#     algorithm.test.num_samples_to_render=0 \
#     algorithm.test.num_samples_to_visualize=0 \
#     algorithm.test.num_directives_to_generate=0 \
#     algorithm.validation.num_samples_to_compute_physical_feasibility_metrics_for=0 \
#     algorithm.classifier_free_guidance.use_floor=True \
#     algorithm.classifier_free_guidance.weight=1.5 \
#     algorithm.ddpo.dynamic_constraint_rewards.use=True \
#     algorithm.ddpo.use_universal_reward=False \
#     algorithm.ddpo.dynamic_constraint_rewards.reward_base_dir=/media/ajad/YourBook/AshokSaugatResearchBackup/AshokSaugatResearch/steerable-scene-generation/dynamic_constraint_rewards \
#     dataset.sdf_cache_dir=./bedroom_sdf_cache/ \
#     dataset.accessibility_cache_dir=./bedroom_accessibility_cache/ \
#     algorithm.custom.num_classes=22 \
#     algorithm.custom.objfeat_dim=0 \
#     algorithm.custom.obj_vec_len=30 \
#     algorithm.custom.obj_diff_vec_len=30 \
#     dataset.data.encoding_type=cached_diffusion_cosin_angle_wocm \
#     dataset.data.dataset_directory=bedroom \
#     dataset.data.annotation_file=bedroom_threed_front_splits_original.csv \
#     dataset.data.room_type=bedroom \
#     algorithm.custom.old=True \
#     algorithm.ddpo.dynamic_constraint_rewards.user_query="Bedroom with a bed at the center of the room ie 0 0 0 position" \
#     algorithm.ddpo.dynamic_constraint_rewards.agentic=False \
#     algorithm.ddpo.dynamic_constraint_rewards.universal_weight=0.0 \
#     wandb.mode=disabled

# PYTHONPATH=. python main.py +name=test\
#     load=rrudae6n \
#     dataset=custom_scene \
#     dataset.processed_scene_data_path=data/metadatas/custom_scene_metadata.json \
#     dataset.max_num_objects_per_scene=12 \
#     algorithm=scene_diffuser_midiffusion \
#     algorithm.classifier_free_guidance.use=False \
#     algorithm.ema.use=True \
#     algorithm.trainer=rl_ppo \
#     algorithm.noise_schedule.scheduler=ddim \
#     algorithm.noise_schedule.ddim.num_inference_timesteps=150 \
#     experiment.training.max_steps=1020000 \
#     experiment.validation.limit_batch=1 \
#     experiment.validation.val_every_n_step=50 \
#     algorithm.ddpo.ddpm_reg_weight=50.0 \
#     experiment.reset_lr_scheduler=True \
#     experiment.training.lr=1e-6 \
#     experiment.lr_scheduler.num_warmup_steps=250 \
#     algorithm.ddpo.batch_size=2 \
#     experiment.training.checkpointing.every_n_train_steps=500 \
#     algorithm.num_additional_tokens_for_sampling=0 \
#     algorithm.ddpo.n_timesteps_to_sample=100 \
#     experiment.find_unused_parameters=True \
#     algorithm.custom.loss=True \
#     algorithm.validation.num_samples_to_render=0 \
#     algorithm.validation.num_samples_to_visualize=0 \
#     algorithm.validation.num_directives_to_generate=0 \
#     algorithm.test.num_samples_to_render=0 \
#     algorithm.test.num_samples_to_visualize=0 \
#     algorithm.test.num_directives_to_generate=0 \
#     algorithm.validation.num_samples_to_compute_physical_feasibility_metrics_for=0 \
#     algorithm.classifier_free_guidance.use_floor=True \
#     algorithm.ddpo.dynamic_constraint_rewards.use=False \
#     algorithm.ddpo.use_universal_reward=True \
#     algorithm.ddpo.dynamic_constraint_rewards.reward_base_dir=/media/ajad/YourBook/AshokSaugatResearchBackup/AshokSaugatResearch/steerable-scene-generation/dynamic_constraint_rewards \
#     dataset.sdf_cache_dir=./bedroom_sdf_cache/ \
#     dataset.accessibility_cache_dir=./bedroom_accessibility_cache/ \
#     algorithm.custom.num_classes=22 \
#     algorithm.custom.objfeat_dim=0 \
#     algorithm.custom.obj_vec_len=30 \
#     algorithm.custom.obj_diff_vec_len=30 \
#     dataset.data.encoding_type=cached_diffusion_cosin_angle_wocm \
#     dataset.data.dataset_directory=bedroom \
#     dataset.data.annotation_file=bedroom_threed_front_splits_original.csv \
#     dataset.data.room_type=bedroom \
#     algorithm.custom.old=True

# PYTHONPATH=. python -u main.py +name=test_no_mix_precision_rl \
#     load=cu8sru1y \
#     dataset=custom_scene \
#     dataset.processed_scene_data_path=data/metadatas/custom_scene_metadata.json \
#     dataset.max_num_objects_per_scene=21 \
#     algorithm=scene_diffuser_midiffusion \
#     algorithm.classifier_free_guidance.use=False \
#     algorithm.ema.use=True \
#     algorithm.trainer=rl_score \
#     algorithm.noise_schedule.scheduler=ddim \
#     algorithm.noise_schedule.ddim.num_inference_timesteps=150 \
#     experiment.training.max_steps=1050000 \
#     experiment.validation.limit_batch=1 \
#     experiment.validation.val_every_n_step=50 \
#     algorithm.ddpo.ddpm_reg_weight=50.0 \
#     experiment.reset_lr_scheduler=True \
#     experiment.training.lr=1e-6 \
#     experiment.lr_scheduler.num_warmup_steps=250 \
#     algorithm.ddpo.batch_size=2 \
#     experiment.training.checkpointing.every_n_train_steps=500 \
#     algorithm.num_additional_tokens_for_sampling=0 \
#     algorithm.ddpo.n_timesteps_to_sample=100 \
#     experiment.find_unused_parameters=True \
#     algorithm.custom.loss=True \
#     algorithm.validation.num_samples_to_render=0 \
#     algorithm.validation.num_samples_to_visualize=0 \
#     algorithm.validation.num_directives_to_generate=0 \
#     algorithm.test.num_samples_to_render=0 \
#     algorithm.test.num_samples_to_visualize=0 \
#     algorithm.test.num_directives_to_generate=0 \
#     algorithm.validation.num_samples_to_compute_physical_feasibility_metrics_for=0 \
#     algorithm.ddpo.use_universal_reward=True \
#     algorithm.classifier_free_guidance.use_floor=True \
#     algorithm.ddpo.dynamic_constraint_rewards.stats_path=dynamic_constraint_rewards/stats.json \
#     dataset.sdf_cache_dir=./living_sdf_cache/ \
#     dataset.accessibility_cache_dir=./living_accessibility_cache/ \
#     algorithm.custom.num_classes=25 \
#     algorithm.custom.objfeat_dim=0 \
#     algorithm.custom.obj_vec_len=33 \
#     algorithm.custom.obj_diff_vec_len=33 \
#     dataset.data.encoding_type=cached_diffusion_cosin_angle_wocm \
#     dataset.data.dataset_directory=livingroom \
#     dataset.data.annotation_file=livingroom_threed_front_splits.csv \
#     dataset.data.room_type=livingroom \
#     algorithm.ddpo.use_inpaint=True \
#     algorithm.custom.old=True \
#     experiment.seed=1

# python scripts/custom_sample_and_render.py +num_scenes=1000 algorithm.noise_schedule.scheduler=ddim algorithm.noise_schedule.ddim.num_inference_timesteps=150 dataset.model_path_vec_len=30 \
#     load=cu8sru1y \
#     dataset=custom_scene \
#     dataset.data.dataset_directory=livingroom \
#     dataset.data.annotation_file=livingroom_threed_front_splits.csv \
#     dataset.data.room_type=livingroom \
#     dataset.processed_scene_data_path=data/metadatas/custom_scene_metadata.json \
#     dataset._name=custom_scene \
#     dataset.max_num_objects_per_scene=21 \
#     algorithm=scene_diffuser_midiffusion \
#     algorithm.trainer=ddpm \
#     algorithm.custom.objfeat_dim=0 \
#     experiment.find_unused_parameters=True \
#     algorithm.classifier_free_guidance.use=False \
#     algorithm.classifier_free_guidance.use_floor=True \
#     algorithm.classifier_free_guidance.weight=0 \
#     algorithm.custom.obj_vec_len=65 \
#     algorithm.custom.obj_diff_vec_len=65 \
#     algorithm.custom.loss=true \
#     algorithm.custom.num_classes=25 \
#     algorithm.validation.num_samples_to_render=0 \
#     algorithm.validation.num_samples_to_visualize=0 \
#     algorithm.validation.num_directives_to_generate=0 \
#     algorithm.test.num_samples_to_render=0 \
#     algorithm.test.num_samples_to_visualize=0 \
#     algorithm.test.num_directives_to_generate=0 \
#     algorithm.validation.num_samples_to_compute_physical_feasibility_metrics_for=0 \
#     dataset.data.encoding_type=cached_diffusion_cosin_angle_objfeats_lat32_wocm \
#     dataset.data.path_to_processed_data=/media/ajad/YourBook/AshokSaugatResearchBackup/AshokSaugatResearch/3d_front_data



# PYTHONPATH=. python -u main.py +name=test_inpaint_rl \
#     dataset=custom_scene \
#     dataset.processed_scene_data_path=data/metadatas/custom_scene_metadata.json \
#     dataset.max_num_objects_per_scene=12 \
#     algorithm=scene_diffuser_midiffusion\
#     algorithm.classifier_free_guidance.use=False \
#     algorithm.ema.use=False \
#     algorithm.trainer=rl_score \
#     algorithm.noise_schedule.scheduler=ddim \
#     algorithm.noise_schedule.ddim.num_inference_timesteps=150 \
#     experiment.training.max_steps=2e6 \
#     experiment.validation.limit_batch=1 \
#     experiment.validation.val_every_n_step=50 \
#     algorithm.ddpo.ddpm_reg_weight=50.0 \
#     experiment.reset_lr_scheduler=True \
#     experiment.training.lr=1e-6 \
#     experiment.lr_scheduler.num_warmup_steps=250 \
#     algorithm.ddpo.batch_size=4 \
#     experiment.training.checkpointing.every_n_train_steps=500 \
#     algorithm.num_additional_tokens_for_sampling=0 \
#     algorithm.ddpo.n_timesteps_to_sample=100 \
#     experiment.find_unused_parameters=True \
#     algorithm.custom.loss=true \
#     algorithm.validation.num_samples_to_render=0 \
#     algorithm.validation.num_samples_to_visualize=0 \
#     algorithm.validation.num_directives_to_generate=0 \
#     algorithm.test.num_samples_to_render=0 \
#     algorithm.test.num_samples_to_visualize=0 \
#     algorithm.test.num_directives_to_generate=0 \
#     algorithm.validation.num_samples_to_compute_physical_feasibility_metrics_for=0 \
#     experiment.training.precision=bf16-mixed \
#     algorithm.ddpo.use_universal_reward=True \
#     algorithm.ddpo.universal_reward.use_physcene_reward=True \
#     algorithm.classifier_free_guidance.use_floor=True \
#     load=rrudae6n \
#     algorithm.classifier_free_guidance.weight=1.0 \
#     algorithm.custom.old=True \
#     algorithm.predict.inpaint_masks='{dining_chair: 10}' \
#     algorithm.ddpo.use_inpaint=True \




# # python scripts/inpaint.py +num_scenes=1000 algorithm.noise_schedule.scheduler=ddim algorithm.noise_schedule.ddim.num_inference_timesteps=150 dataset.model_path_vec_len=30 \
# #     load=cu8sru1y \
# #     dataset=custom_scene \
# #     dataset.data.dataset_directory=livingroom \
# #     dataset.data.annotation_file=livingroom_threed_front_splits.csv \
# #     dataset.data.room_type=livingroom \
# #     dataset.processed_scene_data_path=data/metadatas/custom_scene_metadata.json \
# #     dataset._name=custom_scene \
# #     dataset.max_num_objects_per_scene=21 \
# #     algorithm=scene_diffuser_midiffusion \
# #     algorithm.trainer=ddpm \
# #     algorithm.custom.objfeat_dim=0 \
# #     experiment.find_unused_parameters=True \
# #     algorithm.classifier_free_guidance.use=False \
# #     algorithm.classifier_free_guidance.use_floor=True \
# #     algorithm.classifier_free_guidance.weight=0 \
# #     algorithm.custom.obj_vec_len=65 \
# #     algorithm.custom.obj_diff_vec_len=65 \
# #     algorithm.custom.loss=true \
# #     algorithm.custom.num_classes=25 \
# #     algorithm.validation.num_samples_to_render=0 \
# #     algorithm.validation.num_samples_to_visualize=0 \
# #     algorithm.validation.num_directives_to_generate=0 \
# #     algorithm.test.num_samples_to_render=0 \
# #     algorithm.test.num_samples_to_visualize=0 \
# #     algorithm.test.num_directives_to_generate=0 \
# #     algorithm.validation.num_samples_to_compute_physical_feasibility_metrics_for=0 \
# #     dataset.data.encoding_type=cached_diffusion_cosin_angle_objfeats_lat32_wocm \
# #     dataset.data.path_to_processed_data=/media/ajad/YourBook/AshokSaugatResearchBackup/AshokSaugatResearch/3d_front_data \
# #     algorithm.predict.inpaint_masks='{dining_chair: 10}'

# python scripts/inpaint.py load=cu8sru1y dataset=custom_scene dataset.processed_scene_data_path=data/metadatas/custom_scene_metadata.json dataset._name=custom_scene +num_scenes=1000 algorithm=scene_diffuser_midiffusion algorithm.trainer=ddpm experiment.find_unused_parameters=True algorithm.classifier_free_guidance.use=False algorithm.classifier_free_guidance.use_floor=True algorithm.classifier_free_guidance.weight=0 algorithm.custom.loss=true algorithm.ema.use=True algorithm.noise_schedule.scheduler=ddim algorithm.noise_schedule.ddim.num_inference_timesteps=150  dataset.data.room_type=livingroom dataset.model_path_vec_len=30 dataset.data.path_to_processed_data=/media/ajad/YourBook/AshokSaugatResearchBackup/AshokSaugatResearch/steerable-scene-generation/MiData dataset.data.dataset_directory=livingroom dataset.data.annotation_file=livingroom_threed_front_splits.csv dataset.max_num_objects_per_scene=21 algorithm.custom.objfeat_dim=0 algorithm.custom.obj_vec_len=65 algorithm.custom.obj_diff_vec_len=65 algorithm.custom.num_classes=25 dataset.data.encoding_type=cached_diffusion_cosin_angle_objfeats_lat32_wocm algorithm.validation.num_samples_to_render=0 algorithm.validation.num_samples_to_visualize=0 algorithm.validation.num_directives_to_generate=0 algorithm.test.num_samples_to_render=0 algorithm.test.num_samples_to_visualize=0 algorithm.test.num_directives_to_generate=0 algorithm.validation.num_samples_to_compute_physical_feasibility_metrics_for=0 \
#     dataset.data.path_to_processed_data=/media/ajad/YourBook/AshokSaugatResearchBackup/AshokSaugatResearch/3d_front_data \
#     algorithm.predict.inpaint_masks='{dining_chair: 10}'

# # python test_duplicate.py dataset=custom_scene algorithm=scene_diffuser_midiffusion algorithm.custom.old=true dataset.data.room_type=livingroom dataset.data.dataset_directory=livingroom dataset.data.annotation_file=livingroom_threed_front_splits.csv algorithm.custom.num_classes=25 dataset.max_num_objects_per_scene=21
